services:
  mysql:
    image: mysql:8.0   # MySQL 8.0 image
    container_name: bankapp-dev-db
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"  # Root password from .env file
      MYSQL_DATABASE: "${MYSQL_DATABASE:-bankdb}"   # Database name from .env file or default to bank_db
      MYSQL_USER: "${MYSQL_USER:-bankuser}"         # Database user from .env file or default to bank_user
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"            # Database user password from .env file
    ports:
      - "${MYSQL_PORT:-3307}:3306"                    # Port mapping, host: container, default to 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql                     # Volume mapping, host (persistent): container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
    mysql_data:      # Λέμε στον docker να ορίσει στον host ένα persistent volume
